repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        pass_filenames: false
        args: [
          "-c", "pyproject.toml",
          "-r", "."
          ]
         

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - --config-file=pyproject.toml
          - "."
        additional_dependencies:
          - dj_database_url
          - django-stubs
          - djangorestframework-stubs
          - django-environ
          - django-prometheus
          - djangorestframework
          - djangorestframework-simplejwt
          - drf-spectacular
          - celery
          - redis
          - httpx
          
